include: package:lints/recommended.yaml
analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    # error
    avoid_web_libraries_in_flutter: error
    await_only_futures: error
    body_might_complete_normally: error
    body_might_complete_normally_catch_error: error
    body_might_complete_normally_nullable: error
    collection_methods_unrelated_type: error
    discarded_futures: error
    invalid_non_virtual_annotation: error
    invalid_override_of_non_virtual_member: error
    invalid_use_of_protected_member: error
    iterable_contains_unrelated_type: error
    inference_failure_on_function_invocation: error
    inference_failure_on_function_return_type: error 
    inference_failure_on_collection_literal: error
    inference_failure_on_generic_invocation: error
    inference_failure_on_instance_creation: error
    inference_failure_on_uninitialized_variable: error 
    inference_failure_on_untyped_parameter: error
    list_remove_unrelated_type: error
    must_be_immutable: error
    must_call_super: error
    strict_raw_type: error
    unawaited_futures: error
    unrelated_type_equality_checks: error
    use_build_context_synchronously: error
    valid_regexps: error

    # warning
    cancel_subscriptions: warning
    close_sinks: warning
    only_throw_errors: warning
    prefer_typing_uninitialized_variables: warning
    type_annotate_public_apis: warning

    # ignore
    invalid_annotation_target: ignore

  language: 
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    # error rule
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    control_flow_in_finally: true
    deprecated_member_use_from_same_package: true
    discarded_futures: true
    empty_statements: true
    hash_and_equals: true
    implicit_reopen: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    valid_regexps: true

    # style rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: false
    avoid_multiple_declarations_per_line: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    dangling_library_doc_comments: true
    deprecated_consistency: true
    directives_ordering: true
    file_names: true
    implementation_imports: true
    implicit_call_tearoffs: true
    library_annotations: true
    non_constant_identifier_names: true
    noop_primitive_operations: true
    only_throw_errors: true
    package_api_docs: true
    parameter_assignments: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    sort_child_properties_last: true
    type_annotate_public_apis: true
    type_literal_in_constant_pattern: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_breaks: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_string_in_part_of_directives: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true
    void_checks: true

    # pub rules
    depend_on_referenced_packages: true
    package_names: true
    sort_pub_dependencies: true
