name: dart_oxide_module
description: Support for Rust-style modules/module visibility modifiers for dart libraries, by means of a custom lint and annotations.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer: ^5.0.0
  analyzer_plugin: ^0.11.2
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder: ^0.3.2
  dart_oxide_annotation: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
