name: dart_oxide_core
description: Provides implementations for core features from Rust in Dart.
version: 0.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  stack_trace: ^1.11.0
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_oxide_lints: ^1.1.0
  freezed: ^2.3.2
  lints: ^2.0.1
  spec: ^0.2.3
