name: dart_oxide_core
description: Provides implementations for core features from Rust in Dart.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  stack_trace: ^1.11.0
  tuple: ^2.0.1

dev_dependencies:
  freezed: ^2.3.2
  lints: ^2.0.1
  test: ^1.21.0
  dart_oxide_module: ^0.1.0
  build_runner: ^2.3.3
  spec: ^0.2.3
